# Generated by Django 6.0.3 on 2026-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0002_inventoryitem_delete_vendorcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
