# Generated by Django 6.0.3 on 2026-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('Motherboard', 'Motherboard'), ('PSU', 'PSU'), ('Storage', 'Storage'), ('Case', 'Case'), ('Cooler', 'Cooler'), ('Monitor', 'Monitor'), ('Peripheral', 'Peripheral')], max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specs', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
