# Generated by Django 6.0.3 on 2026-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='image_url',
        ),
        migrations.AddField(
            model_name='components',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='component_images/'),
        ),
    ]
