# Generated by Django 6.0.3 on 2026-05-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAMSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_mhz', models.IntegerField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram_spec', to='pc_build.components')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pc_build.memorygeneration')),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_factor', models.CharField(choices=[('ATX', 'Standard ATX'), ('mATX', 'Micro-ATX'), ('ITX', 'Mini-ITX'), ('E-ATX', 'Extended ATX')], max_length=10)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_spec', to='pc_build.components')),
                ('memory_generation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pc_build.memorygeneration')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pc_build.socket')),
            ],
        ),
        migrations.CreateModel(
            name='CPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_spec', to='pc_build.components')),
                ('supported_memory', models.ManyToManyField(to='pc_build.memorygeneration')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pc_build.socket')),
            ],
        ),
    ]
