# Generated by Django 6.0.3 on 2026-05-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0005_memorygeneration_socket_ramspec_motherboardspec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_form_factor', models.CharField(choices=[('ATX', 'Standard ATX'), ('mATX', 'Micro-ATX'), ('ITX', 'Mini-ITX'), ('E-ATX', 'Extended ATX')], max_length=10)),
                ('max_gpu_length_mm', models.IntegerField(help_text='Maximum length in mm before the GPU hits the front fans')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_spec', to='pc_build.components')),
            ],
        ),
        migrations.CreateModel(
            name='CoolerSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liquid_cooler', models.BooleanField(default=False)),
                ('radiator_size_mm', models.IntegerField(blank=True, help_text='e.g., 240, 360 (Leave blank for air coolers)', null=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooler_spec', to='pc_build.components')),
                ('supported_sockets', models.ManyToManyField(to='pc_build.socket')),
            ],
        ),
        migrations.CreateModel(
            name='GPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.IntegerField(help_text="Must be less than the Case's max_gpu_length_mm")),
                ('recommended_psu_wattage', models.IntegerField(help_text='e.g., 750W minimum recommended by Nvidia/AMD')),
                ('vram_gb', models.IntegerField(help_text='e.g., 12, 16, 24')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_spec', to='pc_build.components')),
            ],
        ),
        migrations.CreateModel(
            name='PSUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.IntegerField(help_text='e.g., 750, 850, 1000')),
                ('efficiency', models.CharField(help_text='e.g., 80+ Gold, 80+ Bronze', max_length=20)),
                ('is_modular', models.BooleanField(default=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psu_spec', to='pc_build.components')),
            ],
        ),
        migrations.CreateModel(
            name='StorageSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_type', models.CharField(choices=[('NVMe', 'NVMe M.2'), ('SATA_SSD', 'SATA 2.5" SSD'), ('HDD', 'SATA 3.5" HDD')], max_length=15)),
                ('capacity_gb', models.IntegerField(help_text='e.g., 1000 for 1TB, 2000 for 2TB')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_spec', to='pc_build.components')),
            ],
        ),
    ]
