# Generated by Django 6.0.3 on 2026-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0006_casespec_coolerspec_gpuspec_psuspec_storagespec'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuspec',
            name='tdp_watts',
            field=models.IntegerField(default=65, help_text='Power consumption in Watts (e.g., 65, 125)'),
        ),
        migrations.AddField(
            model_name='gpuspec',
            name='tdp_watts',
            field=models.IntegerField(default=200, help_text='Power consumption in Watts (e.g., 200, 320)'),
        ),
        migrations.AlterField(
            model_name='gpuspec',
            name='length_mm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpuspec',
            name='recommended_psu_wattage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpuspec',
            name='vram_gb',
            field=models.IntegerField(),
        ),
    ]
